export const smmpanel = [
  {
    platform: "facebook",
    services: [
      {
        type: "followers",
        name: "Followers",
        price_per_unit: 0.07,
        Guarantee: "Lifetime Guarantee",
        description:
          "Increase your facebook followers with real and active accounts.",
        min_quantity: 100,
        max_quantity: 5000,
        delivery_time: "24 hours",
        targeting_options: ["Country", "Gender", "Interest"],
        min_amount: 1000,
        max_amount: 20000,
      },
      {
        type: "likes",
        name: "Likes",
        price_per_unit: 0.03,
        Guarantee: "Lifetime Guarantee",
        description: "Boost the likes on your facebook photos and videos.",
        min_quantity: 50,
        max_quantity: 5000,
        delivery_time: "12 hours",
        min_amount: 1000,
        max_amount: 20000,
      },
    ],
  },
  {
    platform: "twitter",
    services: [
      {
        type: "followers",
        name: "Followers",
        price_per_unit: 0.07,
        Guarantee: "Lifetime Guarantee",
        description:
          "Increase your twitter followers with real and active accounts.",
        min_quantity: 100,
        max_quantity: 5000,
        delivery_time: "24 hours",
        targeting_options: ["Country", "Gender", "Interest"],
        min_amount: 1000,
        max_amount: 20000,
      },
      {
        type: "likes",
        name: "Likes",
        Guarantee: "Lifetime Guarantee",
        price_per_unit: 0.03,
        description: "Boost the likes on your twitter photos and videos.",
        min_quantity: 50,
        max_quantity: 5000,
        delivery_time: "12 hours",
        min_amount: 1000,
        max_amount: 20000,
      },
    ],
  },
  {
    platform: "instagram",
    services: [
      {
        type: "followers",
        name: "Followers",
        price_per_unit: 0.07,
        Guarantee: "Lifetime Guarantee",
        description:
          "Increase your Instagram followers with real and active accounts.",
        min_quantity: 100,
        max_quantity: 5000,
        delivery_time: "24 hours",
        targeting_options: ["Country", "Gender", "Interest"],
        min_amount: 1000,
        max_amount: 20000,
      },
      {
        type: "likes",
        name: "Likes",
        price_per_unit: 0.03,
        Guarantee: "Lifetime Guarantee",
        description: "Boost the likes on your Instagram photos and videos.",
        min_quantity: 50,
        max_quantity: 5000,
        delivery_time: "12 hours",
        min_amount: 1000,
        max_amount: 20000,
      },
    ],
  },
  {
    platform: "youtube",
    services: [
      {
        type: "subscriber",
        name: "subscriber",
        price_per_unit: 0.07,
        Guarantee: "Lifetime Guarantee",
        description:
          "Increase your Instagram subscriber with real and active accounts.",
        min_quantity: 100,
        max_quantity: 5000,
        delivery_time: "24 hours",
        targeting_options: ["Country", "Gender", "Interest"],
        min_amount: 1000,
        max_amount: 20000,
      },
      {
        type: "likes",
        name: "Likes",
        Guarantee: "Lifetime Guarantee",
        price_per_unit: 0.03,
        description: "Boost the likes on your Instagram photos and videos.",
        min_quantity: 50,
        max_quantity: 5000,
        delivery_time: "12 hours",
        min_amount: 1000,
        max_amount: 20000,
      },
      {
        type: "comments",
        name: "comments",
        Guarantee: "Lifetime Guarantee",
        price_per_unit: 0.03,
        description: "Boost the comments on your Instagram photos and videos.",
        min_quantity: 50,
        max_quantity: 5000,
        delivery_time: "12 hours",
        min_amount: 1000,
        max_amount: 20000,
      },
      {
        type: "watchtime",
        name: "watchtime",
        Guarantee: "Lifetime Guarantee",
        price_per_unit: 0.03,
        description: "Boost the watchtime on your Instagram photos and videos.",
        min_quantity: 50,
        max_quantity: 5000,
        delivery_time: "12 hours",
        min_amount: 1000,
        max_amount: 20000,
      },
      {
        type: "shorts",
        name: "shorts",
        Guarantee: "Lifetime Guarantee",
        price_per_unit: 0.01,
        description: "Boost the YouTube Short Video Views",
        min_quantity: 50,
        max_quantity: 5000,
        delivery_time: "12 hours",
        min_amount: 1000,
        max_amount: 20000,
      },
      {
        type: "monetization",
        name: "monetization",
        Guarantee: "Lifetime Guarantee",
        price_per_unit: 180.23,
        description:
          "YouTube Monetization Package [4000 Hours + 1000 Subscribers]",
        min_quantity: 50,
        max_quantity: 5000,
        delivery_time: "30 days",
        min_amount: 1000,
        max_amount: 20000,
      },
    ],
  },
  {
    platform: "Telegram",
    services: [
      {
        type: "members",
        name: "members",
        Guarantee: "Lifetime Guarantee",
        price_per_unit: 0.1,
        description: "Increase Telegram Members",
        min_quantity: 50,
        max_quantity: 5000,
        delivery_time: "30 days",
        min_amount: 1000,
        max_amount: 20000,
      },
      {
        name: "views",
        type: "views",
        price_per_unit: 0.05,
        description: "Boost Telegram Channel Views",
        min_quantity: 100,
        max_quantity: 10000,
        delivery_time: "30 days",
        min_amount: 1000,
        max_amount: 20000,
      },
    ],
  },
  {
    platform: "TikTok",
    services: [
      {
        name: "followers",
        type: "followers",
        price_per_unit: 0.06,
        description: "Buy TikTok Followers",
        min_quantity: 100,
        max_quantity: 5000,
        delivery_time: "30 days",
        min_amount: 1000,
        max_amount: 20000,
      },
      {
        name: "likes",
        type: "likes",
        price_per_unit: 0.03,
        description: "Buy TikTok Likes",
        min_quantity: 50,
        max_quantity: 5000,
        delivery_time: "30 days",
        min_amount: 1000,
        max_amount: 20000,
      },
      {
        name: "views",
        type: "views",
        price_per_unit: 0.04,
        description: "Buy TikTok Views",
        min_quantity: 1000,
        max_quantity: 100000,
        delivery_time: "30 days",
        min_amount: 1000,
        max_amount: 20000,
      },
    ],
  },

  {
    platform: "Spotify",
    services: [
      {
        name: "plays",
        type: "plays",
        price_per_unit: 0.004,
        description: "Get Spotify Plays",
        min_quantity: 1000,
        max_quantity: 100000,
        delivery_time: "30 days",
        min_amount: 1000,
        max_amount: 20000,
      },
      {
        name: "followers",
        type: "followers",
        price_per_unit: 0.07,
        description: "Increase Spotify Followers",
        min_quantity: 1000,
        max_quantity: 100000,
        delivery_time: "30 days",
        min_amount: 1000,
        max_amount: 20000,
      },
      {
        type: "playlist_placement",
        price_per_unit: 10,
        description: "Get Playlist Placement",
        min_quantity: 1000,
        max_quantity: 100000,
        delivery_time: "30 days",
        min_amount: 1000,
        max_amount: 20000,
      },
    ],
  },
  {
    platform: "SoundCloud",
    services: [
      {
        name: "plays",
        type: "plays",
        price_per_unit: 0.002,
        description: "Get SoundCloud Plays",
        min_quantity: 1000,
        max_quantity: 100000,
        delivery_time: "30 days",
        min_amount: 1000,
        max_amount: 20000,
      },
      {
        name: "followers",
        type: "followers",
        price_per_unit: 0.05,
        description: "Increase SoundCloud Followers",
        min_quantity: 1000,
        max_quantity: 100000,
        delivery_time: "30 days",
        min_amount: 1000,
        max_amount: 20000,
      },
      {
        name: "likes",
        type: "likes",
        price_per_unit: 0.04,
        description: "Get SoundCloud Likes",
        min_quantity: 1000,
        max_quantity: 100000,
        delivery_time: "30 days",
        min_amount: 1000,
        max_amount: 20000,
      },
    ],
  },
  {
    platform: "LinkedIn",
    services: [
      {
        name: "connections",
        type: "connections",
        price_per_unit: 0.1,
        description: "Increase LinkedIn Connections",
        min_quantity: 1000,
        max_quantity: 100000,
        delivery_time: "30 days",
        min_amount: 1000,
        max_amount: 20000,
      },
      {
        name: "post likes",
        type: "post likes",
        price_per_unit: 0.06,
        description: "Get LinkedIn Post Likes",
        min_quantity: 1000,
        max_quantity: 100000,
        delivery_time: "30 days",
        min_amount: 1000,
        max_amount: 20000,
      },
      {
        name: "shares",
        type: "shares",
        price_per_unit: 0.08,
        description: "Share LinkedIn Posts",
        min_quantity: 1000,
        max_quantity: 100000,
        delivery_time: "30 days",
        min_amount: 1000,
        max_amount: 20000,
      },
    ],
  },
  {
    platform: "Discord",
    services: [
      {
        name: "members",
        type: "members",
        price_per_unit: 0.1,
        description: "Increase Discord Members",
        min_quantity: 1000,
        max_quantity: 100000,
        delivery_time: "30 days",
        min_amount: 1000,
        max_amount: 20000,
      },
      {
        name: "messages",
        type: "messages",
        price_per_unit: 0.04,
        description: "Send Discord Messages",
        min_quantity: 1000,
        max_quantity: 100000,
        delivery_time: "30 days",
        min_amount: 1000,
        max_amount: 20000,
      },
    ],
  },
  {
    platform: "Pinterest",
    services: [
      {
        name: "pins",
        type: "pins",
        price_per_unit: 0.06,
        description: "Pin content on Pinterest",
        min_quantity: 1000,
        max_quantity: 100000,
        delivery_time: "30 days",
        min_amount: 1000,
        max_amount: 20000,
      },
      {
        name: "repins",
        type: "repins",
        price_per_unit: 0.05,
        description: "Repin content on Pinterest",
        min_quantity: 1000,
        max_quantity: 100000,
        delivery_time: "30 days",
        min_amount: 1000,
        max_amount: 20000,
      },
      {
        name: "followers",
        type: "followers",
        price_per_unit: 0.08,
        description: "Increase Pinterest Followers",
        min_quantity: 1000,
        max_quantity: 100000,
        delivery_time: "30 days",
        min_amount: 1000,
        max_amount: 20000,
      },
    ],
  },
  {
    platform: "Website",
    services: [
      {
        name: "traffic",
        type: "traffic",
        price_per_unit: 0.05,
        description: "Increase Website Traffic",
        min_quantity: 1000,
        max_quantity: 100000,
        delivery_time: "30 days",
        min_amount: 1000,
        max_amount: 20000,
      },
      {
        name: "comments",
        type: "comments",
        price_per_unit: 0.08,
        description: "Get Comments on Blog Posts",
        min_quantity: 1000,
        max_quantity: 100000,
        delivery_time: "30 days",
        min_amount: 1000,
        max_amount: 20000,
      },
      {
        name:"backlinks",
        type: "backlinks",
        price_per_unit: 5,
        description: "Acquire Backlinks",
        min_quantity: 1000,
        max_quantity: 100000,
        delivery_time: "30 days",
        min_amount: 1000,
        max_amount: 20000,
      },
    ],
  },
];
