export const smm_data = [
  {
    platform: "youtube",
    name: "subscriber",
    type: "subscriber",
    tags: "none droped,Lifetime Guarantee,Positive,Mixed 👍🤩🎉🔥❤️,EMERGENCY,Refill Lifetime,VERY FAST ,♻️⚡📌NEW",
    price_per_unit: "0.2168",
    delivery_time: "34hour",
    min_quantity: "10",
    max_quantity: "200000",
    dripfeed: false,
    refill: false,
    cancel: true,
  },
  {
    platform: "youtube",
    name: "views",
    type: "views",
    tags: "none droped,Lifetime Guarantee,Positive,Mixed 👍🤩🎉🔥❤️,EMERGENCY,Refill Lifetime,VERY FAST ,♻️⚡📌NEW",
    price_per_unit: "0.2168",
    delivery_time: "34hour",
    min_quantity: "10",
    max_quantity: "200000",
    dripfeed: false,
    refill: false,
    cancel: true,
  },
  {
    platform: "youtube",
    name: "comments",
    type: "comments",
    tags: "none droped,Lifetime Guarantee,Positive,Mixed 👍🤩🎉🔥❤️,EMERGENCY,Refill Lifetime,VERY FAST ,♻️⚡📌NEW",
    price_per_unit: "0.2168",
    delivery_time: "34hour",
    min_quantity: "10",
    max_quantity: "200000",
    dripfeed: false,
    refill: false,
    cancel: true,
  },
  {
    platform: "youtube",
    name: "watchtime",
    type: "watchtime",
    tags: "none droped,Lifetime Guarantee,Positive,Mixed 👍🤩🎉🔥❤️,EMERGENCY,Refill Lifetime,VERY FAST ,♻️⚡📌NEW",
    price_per_unit: "0.2168",
    delivery_time: "34hour",
    min_quantity: "10",
    max_quantity: "200000",
    dripfeed: false,
    refill: false,
    cancel: true,
  },
  {
    platform: "youtube",
    name: "likes",
    type: "likes",
    tags: "none droped,Lifetime Guarantee,Positive,Mixed 👍🤩🎉🔥❤️,EMERGENCY,Refill Lifetime,VERY FAST ,♻️⚡📌NEW",
    price_per_unit: "0.2168",
    delivery_time: "34hour",
    min_quantity: "10",
    max_quantity: "200000",
    dripfeed: false,
    refill: false,
    cancel: true,
  },
  {
    platform: "telegram",
    name: "views",
    type: "views",
    tags: "none droped,Lifetime Guarantee,Positive,Mixed 👍🤩🎉🔥❤️,EMERGENCY,Refill Lifetime,VERY FAST ,♻️⚡📌NEW",
    price_per_unit: "0.2168",
    delivery_time: "34hour",
    min_quantity: "10",
    max_quantity: "200000",
    dripfeed: false,
    refill: false,
    cancel: true,
  },
  {
    platform: "telegram",
    name: "member",
    type: "member",
    tags: "none droped,Lifetime Guarantee,Positive,Mixed 👍🤩🎉🔥❤️,EMERGENCY,Refill Lifetime,VERY FAST ,♻️⚡📌NEW",
    price_per_unit: "0.2168",
    delivery_time: "34hour",
    min_quantity: "10",
    max_quantity: "200000",
    dripfeed: false,
    refill: false,
    cancel: true,
  },

  {
    platform: "linkedin",
    name: "connections",
    type: "connections",
    tags: "none droped,Lifetime Guarantee,Positive,Mixed 👍🤩🎉🔥❤️,EMERGENCY,Refill Lifetime,VERY FAST ,♻️⚡📌NEW",
    price_per_unit: "0.2168",
    delivery_time: "34hour",
    min_quantity: "10",
    max_quantity: "200000",
    dripfeed: false,
    refill: false,
    cancel: true,
  },
  {
    platform: "linkedin",
    name: "post likes",
    type: "post likes",
    tags: "none droped,Lifetime Guarantee,Positive,Mixed 👍🤩🎉🔥❤️,EMERGENCY,Refill Lifetime,VERY FAST ,♻️⚡📌NEW",
    price_per_unit: "0.2168",
    delivery_time: "34hour",
    min_quantity: "10",
    max_quantity: "200000",
    dripfeed: false,
    refill: false,
    cancel: true,
  },
  {
    platform: "linkedin",
    name: "shares",
    type: "shares",
    tags: "none droped,Lifetime Guarantee,Positive,Mixed 👍🤩🎉🔥❤️,EMERGENCY,Refill Lifetime,VERY FAST ,♻️⚡📌NEW",
    price_per_unit: "0.2168",
    delivery_time: "34hour",
    min_quantity: "10",
    max_quantity: "200000",
    dripfeed: false,
    refill: false,
    cancel: true,
  },
  {
    platform: "facebook",
    name: "likes",
    type: "likes",
    tags: "none droped,Lifetime Guarantee,Positive,Mixed 👍🤩🎉🔥❤️,EMERGENCY,Refill Lifetime,VERY FAST ,♻️⚡📌NEW",
    price_per_unit: "0.2168",
    delivery_time: "34hour",
    min_quantity: "10",
    max_quantity: "200000",
    dripfeed: false,
    refill: false,
    cancel: true,
  },
  {
    platform: "facebook",
    name: "follower",
    type: "follower",
    tags: "none droped,Lifetime Guarantee,Positive,Mixed 👍🤩🎉🔥❤️,EMERGENCY,Refill Lifetime,VERY FAST ,♻️⚡📌NEW",
    price_per_unit: "0.2168",
    delivery_time: "34hour",
    min_quantity: "10",
    max_quantity: "200000",
    dripfeed: false,
    refill: false,
    cancel: true,
  },

  {
    platform: "instagram",
    name: "likes",
    type: "likes",
    tags: "none droped,Lifetime Guarantee,Positive,Mixed 👍🤩🎉🔥❤️,EMERGENCY,Refill Lifetime,VERY FAST ,♻️⚡📌NEW",
    price_per_unit: "0.2168",
    delivery_time: "34hour",
    min_quantity: "10",
    max_quantity: "200000",
    dripfeed: false,
    refill: false,
    cancel: true,
  },
  {
    platform: "instagram",
    name: "follower",
    type: "follower",
    tags: "none droped,Lifetime Guarantee,Positive,Mixed 👍🤩🎉🔥❤️,EMERGENCY,Refill Lifetime,VERY FAST ,♻️⚡📌NEW",
    price_per_unit: "0.2168",
    delivery_time: "34hour",
    min_quantity: "10",
    max_quantity: "200000",
    dripfeed: false,
    refill: false,
    cancel: true,
  },
];
